spring.application.name=meetingService


server.port=8092

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# spring.data.mongodb.uri=mongodb+srv://rdevananda27:zzQigaRJXWHkg11T@trialproject.zkcmk.mongodb.net/meetingdb?retryWrites=true&w=majority&appName=trialProject

spring.data.mongodb.uri=mongodb://localhost:27017/capstone