spring.application.name=meetingParticipantsService

server.port=8093

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# spring.data.mongodb.uri=mongodb+srv://rdevananda27:zzQigaRJXWHkg11T@trialproject.zkcmk.mongodb.net/meetingparticipantsdb?retryWrites=true&w=majority&appName=trialProject

spring.data.mongodb.uri=mongodb://localhost:27017/capstone